<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Modal;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Framework\Escaper;
use Magento\Review\Block\Product\View as ProductReview;
//use Magento\Theme\Block\Html\Pager;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var ProductReview $block */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaper */
/** @var Pager $toolbar */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var $ReviewModal */
$ReviewModal = $viewModels->require(Modal::class)
    ->createModal()
    ->withDialogRefName("review-modal")
    ->withContent("<div id='review-list'><div class='p-20'>{$escaper->escapeHtml(__('Reviews worden geladen ...'))}</div></div>")
    ->withAriaLabelledby('review-list')
    ->positionTopRight()
    ->addContainerClass('!pt-0','!pr-0', '!z-[999]')
    ->addDialogClass( 'md:max-w-4xl')
    ->removeDialogClass('p-10', 'rounded-lg');

$reviewCollection = $block->getReviewsCollection();
$reviewCollection->load()->addRateVotes();

$items = $reviewCollection->getItems();
$counter = 0;

$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
$formatLong = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
$headingTag = $block->getData('heading_tag') ?: 'h3';
$productName = $block->getProduct()->getName();
$counter = 1;
$sku = $block->getProduct()->getSku();

?>
<?php if (count($items)): ?>
        <div
            class="mx-auto py-6 items-center"
            id="customer-review-list"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Customer Reviews')) ?>"
            tabindex="-1"
            role="group"
        >
        <div class="-mx-6 px-6 flex flex-col pt-6 pb-3 mb-6 border-t border-gray-300 bg-gradient-to-b from-gray-50 to-transparent">
            <?php if (!$block->getHideTitle()): ?>
            <<?= /* @noEscape */ $headingTag ?> class="text-gray-900 text-2xl title-font font-base w-full">
            <?= $escaper->escapeHtml(__('Customer Reviews')) ?>
        </<?= /* @noEscape */ $headingTag ?>>
        <?php endif ?>
        <div class="block mt-2">Algemene beoordeling</div>
        <?= $block->getLayout()->createBlock("Magento\Catalog\Block\Product\View")->setTemplate("Magento_Catalog::product/view/review_section.phtml")->toHtml() ?>
    </div>
    <div class="w-full">
        <?php foreach ($items as $review): ?>
            <?php if ($counter > 4) break; ?>
            <div itemscope itemprop="review" itemtype="http://schema.org/Review"
                 class="pb-4 my-4 last:border-0 last:mb-0 flex flex-col prose border-t py-4">
                <time
                    class="inline-block p-2 self-start bg-lego-blue-lighter text-xs mb-2"
                    itemprop="datePublished"
                    datetime="<?= $escaper->escapeHtmlAttr($block->formatDate($review->getCreatedAt(), $format)); ?>"
                >
                                <span>
                                    <?= $escaper->escapeHtml(
                                        $block->formatDate(
                                            $review->getCreatedAt(),
                                            $formatLong
                                        )
                                    ) ?>
                                </span>
                </time>
                <div>
                    <strong itemprop="author" itemscope itemtype="https://schema.org/Person">
                        <span class="text-lego-blue-light" itemprop="name"><?= $escaper->escapeHtml($review->getNickname()) ?></span>
                    </strong>
                </div>
                <?php //if (count($review->getRating())): ?>
                <div class="table">
                    <?php foreach ($review->getRatingVotes() as $vote): ?>
                        <?php
                        $rating         = $vote->getPercent();
                        $ratingSteps    = 5;
                        $starsFilled    = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
                        $starsEmpty     = floor($ratingSteps - $starsFilled);
                        ?>
                        <div class="table-row" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                            <div
                                class="flex flex-row items-center"
                                role="img"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('%1 rating. %2 out of %3 stars', $productName, $starsFilled, $ratingSteps))?>"
                            >
                                <?php $i = 0; ?>
                                <?php while ($i < $starsFilled): ?>
                                    <?= $heroiconsSolid->starHtml('text-lego-yellow', 24, 24, ["aria-hidden" => "true"]); ?>
                                    <?php $i++; ?>
                                <?php endwhile; ?>
                                <?php $i = 0; ?>
                                <?php while ($i < $starsEmpty): ?>
                                    <?= $heroiconsSolid->starHtml('text-gray-400', 24, 24, ["aria-hidden" => "true"]); ?>
                                    <?php $i++; ?>
                                <?php endwhile; ?>
                                <span class="text-lego-blue-dark text-sm ml-4" itemprop="ratingValue"><?= /** @noEscape */ $starsFilled  . " / " . $ratingSteps; ?></span>
                            </div>
                        </div>

                    <?php endforeach; ?>
                </div>
                <?php // endif; ?>
                <div class="font-semibold" itemprop="name">
                    <?= $escaper->escapeHtml($review->getTitle()) ?>
                </div>
                <div class="mt-1" itemprop="description">
                    <?= /* @noEscape */ nl2br($escaper->escapeHtml($review->getDetail())) ?>
                </div>
            </div>
            <?php $counter++; ?>
        <?php endforeach; ?>
    </div>
    <script>
        function fetchReviewModalContent() {
            let reviewsLoaded = false
            return {
                reviews: [],
                currentPage: 1,
                totalPages: 1,
                loadContent() {
                    if (reviewsLoaded) return

                    let query =
                        `{
                        products(filter: {sku: {eq: "<?= $sku ?>"}}) {
                        items {
                            review_count
                            rating_summary
                            reviews(pageSize: 99, currentPage: 1) {
                                items {
                                    created_at
                                    nickname
                                    summary
                                    text
                                    average_rating
                                    }
                                }
                            }
                        }
                    }`;

                    fetch('/graphql', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                        },
                        body: JSON.stringify({
                            query: query
                        }),
                    })
                        .then(response => response.json())
                        .then(data => {
                            reviewsLoaded = true;
                            this.reviews = data.data.products.items[0].reviews.items;
                            this.totalPages = Math.ceil(data.data.products.items[0].review_count / 10);

                            // Build the Alpine.js template
                            let reviewsHtml =   '<div class="flex bg-lego-blue-dark py-4">' +
                                                '<h2 class="text-white text-2xl title-font font-base self-center">Klantenreviews</h2>' +
                                                '<button class="text-white self-end"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" /></svg></button>' +
                                                '</div>' +
                                                '<div class="table px-10">';

                            this.reviews.forEach(review => {

                                let date = new Date(review.created_at);
                                let shortDate = date.toLocaleDateString('nl-NL');
                                let longDate = date.toLocaleDateString('nl-NL', {  day: 'numeric', month: 'long', year: 'numeric' });
                                const ratingSteps = 5;
                                let rating = review.average_rating;
                                let starsFilled = !isNaN(rating) ? Math.floor(rating / 100 * ratingSteps) : 0;
                                let starsEmpty = Math.floor(ratingSteps - starsFilled);

                                reviewsHtml += `
                                                <div itemscope itemprop="review" itemtype="http://schema.org/Review"
                                                     class="pb-4 my-4 last:border-0 last:mb-0 flex flex-col prose border-t py-4">
                                                    <time
                                                        class="inline-block p-2 self-start bg-lego-blue-lighter text-xs mb-2"
                                                        itemprop="datePublished"
                                                        datetime="${shortDate}"
                                                    >
                                                    <span>${longDate}</span>
                                                   </time>
                                                <div>
                                                    <strong itemprop="author" itemscope itemtype="https://schema.org/Person">
                                                        <span class="text-lego-blue-light" itemprop="name">${review.nickname}</span>
                                                    </strong>
                                                </div>
                                                <div class="table">
                                                    <div class="table-row" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                                        <div class="flex flex-row items-center"
                                                            role="img"
                                                            aria-label=""
                                                        >
                                                        <span class="text-lego-blue-dark text-sm flex flex-row items-center" itemprop="ratingValue">`;

                                                        while (starsFilled > 0) {
                                                            reviewsHtml += `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="text-lego-yellow" width="24" height="24" aria-hidden="true">
                                                                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                                                            </svg>`;
                                                            starsFilled--;
                                                        }
                                reviewsHtml += starsFilled + " / " + ratingSteps;
                                reviewsHtml += `            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="mt-1 font-semibold" itemprop="description">${review.summary}</div>
                                                <div itemprop="name">${review.text}</div>

                                            `;
                            });
                            document.getElementById('review-list').innerHTML = reviewsHtml;
                        })
                        .catch(console.error);
                },
                addEventListener() {
                    document.addEventListener('fetchReviews', this.loadContent);
                },
            }
        }

        // Initialize the fetchReviewModalContent object and add the event listener
        const reviewModalContent = fetchReviewModalContent();
        reviewModalContent.addEventListener();

        // Get the #reviewsLoader button and add a click event listener
        const reviewsLoaderButton = document.getElementById('reviewsLoader');
        reviewsLoaderButton.addEventListener('click', function() {
            // Dispatch the custom event when the button is clicked
            const event = new Event('fetchReviews');
            document.dispatchEvent(event);
        });
    </script>
    <div x-data="hyva.modal(), fetchReviewModalContent()">
        <button id="reviewsLoader" @click="<?= $escaper->escapeHtmlAttr($ReviewModal->getShowJs()) ?>; $dispatch('fetchReviews')" class="btn btn-primary rounded-4xl mt-4 self-start">
            <span class="block mx-auto my-2"><?= $escaper->escapeHtml(__('Show All Reviews')) ?></span>
        </button>
        <?= $ReviewModal;?>
    </div>

<?php endif; ?>
