<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\ProductPage;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var Product $product */
$product = $productViewModel->getProduct();

if (!$product->getDescription()) {
    return;
}

$cssClasses = $block->getData('css_classes') ?? 'prose';
?>
<div class="text-container" x-data="{ open: false }" :class="{'open':open}">
    <div class="<?= $escaper->escapeHtmlAttr($cssClasses) ?> text-content">
        <?= $productViewModel->productAttributeHtml($product, $product->getDescription(), 'description') ?>
        <?= $productViewModel->productAttributeHtml($product, $product->getData('specifications'), 'specifications') ?>
    </div>
    <button @click="open = true" class="read-more"><?= $escaper->escapeHtml(__('Read more')) ?></button>
    <button @click="open = false" class="read-less"><?= $escaper->escapeHtml(__('Read less')) ?></button>
</div>

