<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Details $block */
/** @var Escaper $escaper */

use Magento\Catalog\Block\Product\View\Details;
use Magento\Framework\Escaper;

$titleRenderer = $block->getChildBlock('product.section.title.renderer');
$defaultTitleTemplate = $titleRenderer->getTemplate();

?>
<div>
<?php
foreach ($block->getGroupSortedChildNames('detailed_info', '') as $sectionName) {
    $sectionBlock  = $block->getLayout()->getBlock($sectionName);
    $sectionHtml   = (string) $sectionBlock->toHtml();
    $titleTemplate = $sectionBlock->getData('title_template') ?? $defaultTitleTemplate;

    if (empty(trim($sectionHtml))) {
        continue;
    }
    ?>
    <section id="<?= $escaper->escapeHtmlAttr($sectionBlock->getNameInLayout()) ?>">
        <?=
            $titleRenderer->setTemplate($titleTemplate)
                          ->assign('sectionBlock', $sectionBlock)
                          ->toHtml()
        ?>
        <div class="card w-full">
            <?= /** @noEscape  */ $sectionHtml ?>
        </div>
    </section>
<?php } ?>
</div>
