<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Catalog\Block\Product\View\Gallery;
use Magento\Catalog\Helper\Image;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Gallery $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, [$block, 'isMainImage']));

if (!empty($images) && empty($mainImage)) {
    $mainImage = reset($images);
}

/** @var Image $helper */
$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

$smallWidth = $block->getImageAttribute('product_page_image_small', 'width', 90);
$smallHeight = $block->getImageAttribute('product_page_image_small', 'height', 90);
$mediumWidth = $block->getImageAttribute('product_page_image_medium', 'width', 700);
$mediumHeight = $block->getImageAttribute('product_page_image_medium', 'height', 700);

$galleryOptionNavVertical = (string) $block->getVar('gallery/navdir', 'Magento_Catalog') === 'vertical';
$galleryOptionAllowfullscreen = (bool) $block->getVar('gallery/allowfullscreen', 'Magento_Catalog');
$galleryOptionLoop = (bool) $block->getVar('gallery/loop', 'Magento_Catalog');
$galleryOptionArrows = $block->getVar('gallery/arrows', 'Magento_Catalog');
$galleryOptionShowCaption = (bool) $block->getVar('gallery/caption', 'Magento_Catalog');
$galleryOptionShowDots = (string) $block->getVar('gallery/nav', 'Magento_Catalog') === 'dots';
$galleryOptionShowFullscreenIcon = (bool) $block->getVar('gallery/fullscreenicon', 'Magento_Catalog');
$galleryOptionAppendOnReceive = (string) $block->getVar('gallery_switch_strategy', 'Magento_ConfigurableProduct') === 'append';

$productName = $block->getProduct()->getName();
?>

<div
    class="w-full md:pt-0 md:h-auto md:row-start-1 md:row-span-2 md:col-start-1"
    style="
        --gallery-ratio: <?= /* @noEscape */ $mediumWidth . '/' . $mediumHeight ?>;
        --gallery-width: <?= /* @noEscape */ $mediumWidth ?>px;
    "
>
    <section
        id="gallery"
        aria-label="<?= $escaper->escapeHtml(__('%1 Gallery', $productName)) ?>"
        x-data="initGallery()"
        x-bind="eventListeners"
        class="splide max-w-full h-full w-[var(--gallery-width)]"
    >
        <div class="relative">
            <div
                class="max-w-full w-[var(--gallery-width)] aspect-[var(--gallery-ratio)]"
                aria-hidden="true"
                x-show="fullscreen"
            ></div>
            <div
                class="z-50 backdrop"
                aria-hidden="true"
                x-show="fullscreen"
                x-transition.opacity
                @click="fullscreen = false"
            ></div>
            <div
                class="relative grid bg-container-darker rounded-lg aspect-[var(--gallery-ratio)]"
                :class="{
                    'z-50 fixed inset-0 w-screen max-w-[min(1280px,(100%_-_2rem))] max-h-[min(1024px,(100%_-_2rem))] m-auto': fullscreen,
                    'relative': !fullscreen
                }"
                aria-live="polite"
                aria-atomic="true"
                x-ref="galleryDialog"
                :role="fullscreen ? 'dialog' : false"
                :aria-modal="fullscreen"
                :aria-label="fullscreen ? '<?= $escaper->escapeJs(__('Fullscreen Gallery')) ?>' : false"
            >
                <div class="splide__track">
                    <ul class="splide__list">
                        <template x-for="(image, index) in images" :key="index">
                            <li class="splide__slide flex flex-col justify-center items-center">
                                <figure>
                                    <template x-if="activeItem === index && activeVideo">
                                        <iframe
                                            class="absolute inset-0 aspect-video max-w-full max-h-full h-auto m-auto"
                                            width="1280"
                                            height="720"
                                            type="text/html"
                                            frameborder="0"
                                            loading="lazy"
                                            x-data="getVideoData(image)"
                                            :src="src"
                                            :alt="image.caption || '<?= $escaper->escapeJs($productName) ?>'"
                                            :title="image.caption || '<?= $escaper->escapeJs($productName) ?>'"
                                            :allow="allow"
                                        ></iframe>
                                    </template>
                                    <template x-if="image.type === 'image'">
                                        <img
                                            width="<?= /* @noEscape */ $mediumWidth ?>"
                                            height="<?= /* @noEscape */ $mediumHeight ?>"
                                            class="max-w-full max-h-full m-auto"
                                            :class="{ 'w-auto': fullscreen, 'invisible': activeVideo }"
                                            :src="fullscreen ? image.full : image.img"
                                            :alt="image.caption || '<?= $escaper->escapeJs($productName) ?>'"
                                            :loading="activeItem !== index ? 'lazy' : 'eager'"
                                        >
                                    </template>
                                    <?php if ($galleryOptionShowCaption): ?>
                                        <template x-if="image.type === 'image' && image.caption && image.caption !== '<?= $escaper->escapeJs($productName) ?>'">
                                            <figcaption
                                                class="absolute inset-x-0 bottom-0 pt-4 pb-2 px-4 text-sm xl:text-base font-bold bg-gradient-to-t from-black/10
                                                <?= $galleryOptionArrows !== "start" && $galleryOptionArrows !== "end" ? 'text-center' : 'text-left' ?>
                                                <?= $galleryOptionArrows === "start" ? 'text-right' : '' ?>"
                                                x-text="image.caption"
                                            ></figcaption>
                                        </template>
                                    <?php endif; ?>
                                </figure>
                            </li>
                        </template>
                    </ul>
                </div>
                <?php if ($galleryOptionAllowfullscreen): ?>
                    <button
                        class="absolute inset-0 -outline-offset-2"
                        title="<?= $escaper->escapeHtml(__('Open fullscreen')) ?>"
                        aria-label="<?= $escaper->escapeHtml(__('Open fullscreen')) ?>"
                        x-show="!fullscreen && !activeVideo"
                        x-cloak
                        @click="fullscreen = true"
                    >
                        <?php if ($galleryOptionShowFullscreenIcon): ?>
                            <span class="block absolute top-2 right-2" aria-hidden="true">
                                <span class="block p-2 rounded-full transition shadow hover:shadow-primary/30 focus:shadow-primary/30 bg-white text-primary/50 hover:text-primary focus:text-primary">
                                    <?= $heroicons->arrowsExpandHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
                                </span>
                            </span>
                        <?php endif; ?>
                    </button>
                    <button
                        class="fixed top-2 right-2 lg:top-6 lg:right-6 p-2 rounded-full transition shadow hover:shadow-primary/30 focus:shadow-primary/30 bg-white text-primary"
                        title="<?= $escaper->escapeHtml(__('Close fullscreen')) ?>"
                        aria-label="<?= $escaper->escapeHtml(__('Close fullscreen')) ?>"
                        x-show="fullscreen"
                        @click="fullscreen = false"
                    >
                        <?= $heroicons->xHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
                    </button>
                <?php endif; ?>
                <?php if ($galleryOptionArrows): ?>
                    <div class="splide__arrows z-10 absolute bottom-[50%] flex justify-between gap-2
                        <?= $galleryOptionArrows !== "start" ? 'right-4 md:right-2 lg:right-4 xl:right-8' : '' ?>
                        <?= $galleryOptionArrows !== "end" ? 'left-4 md:left-2 lg:left-4 xl:left-8' : '' ?>"
                    >
                        <button class="splide__arrow splide__arrow--prev shrink-0 p-1.5 rounded-full transition disabled:opacity-30 shadow hover:shadow-primary/30 focus:shadow-primary/30 bg-lego-blue-light text-white">
                            <?= $heroiconsSolid->chevronLeftHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                        </button>
                        <button class="splide__arrow splide__arrow--next shrink-0 p-1.5 rounded-full transition disabled:opacity-30 shadow hover:shadow-primary/30 focus:shadow-primary/30 bg-lego-blue-light text-white">
                            <?= $heroiconsSolid->chevronRightHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                        </button>
                    </div>
                <?php endif; ?>
            </div>
            <ul class="splide__pagination p-2 gap-2"></ul>
        </div>
    </section>
    <script>
        function initGallery() {
            return {
                gallery: null,
                activeItem: 0,
                activeVideo: false,
                fullscreen: false,
                videoOptions: {
                    autoplay: true,
                    loop: false,
                    allowApi: false
                },
                initialImages: <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                images: <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                init() {
                    this.$nextTick(() => {
                        this.initSlider();
                    });
                    this.$watch('fullscreen', (open) => {
                        // *1: Required to keep the slider in sync
                        this.refreshSlider(); // *1

                        this.$nextTick(() => {
                            this.goToSlide(this.activeItem); // *1
                            this.scrollLock(open);
                            this.tabLock(this.$refs.galleryDialog, open);
                        })
                    })
                },
                initSlider() {
                    // NOTE: Dynamic Alpine Sliders don't play nice with the loop option,
                    // this creates clones of the slides which breaks the images render,
                    // So only use the type options: fade or slide
                    this.gallery = new Splide(this.$root, {
                        type: 'slide',
                        rewind: <?= /* @noEscape */ $galleryOptionLoop ? 'true' : 'false' ?>,
                        perPage: 1,
                        gap: 0,
                        drag: false,
                        keyboard: true,
                        slideFocus: true,
                        arrow: <?= /* @noEscape */ $galleryOptionArrows ? 'true' : 'false' ?>,
                        pagination: <?= /* @noEscape */ $galleryOptionShowDots ? 'true' : 'false' ?>,
                        paginationDirection: '<?= /* @noEscape */ $galleryOptionNavVertical ? 'ttb' : 'ltr' ?>',
                        classes: {
                            // Pagination dots style
		                    page: 'splide__pagination__page block rounded-full w-3 h-3 border-2 border-slate-200 transition duration-300 ease-out hover:border-slate-300 hover:bg-slate-300 aria-selected:bg-lego-blue-light aria-selected:border-lego-blue-light',
                        },
                    });

                    this.gallery.on('moved', (newIndex) => {
                        this.activeItem = newIndex;
                        this.activeVideo = this.images[newIndex].type === 'video';
                    });

                    this.gallery.mount();
                },
                refreshSlider() {
                    if (!this.gallery) return;
                    this.gallery.refresh();
                },
                goToSlide(index) {
                    if (!this.gallery) return;
                    if (!index) return;
                    this.gallery.go(index);
                },
                scrollLock(use = true) {
                    document.body.style.overflow = use ? "hidden" : "";
                },
                tabLock(target, use = true) {
                    if (!use) {
                        hyva.releaseFocus(target);
                        return;
                    }

                    hyva.trapFocus(target);
                },
                getVideoData(source) {
                    const videoUrl = source.videoUrl;
                    if (!videoUrl) return;

                    const videoData = {
                        id: null,
                        type: null,
                        src: null,
                        additionalParams: "",
                        allow: "fullscreen; picture-in-picture;"
                    }

                    if (this.videoOptions.autoplay) {
                        videoData.additionalParams += '&autoplay=1';
                        videoData.allow += ' autoplay;';
                    }

                    if (this.videoOptions.loop) {
                        videoData.additionalParams += '&loop=1';
                    }

                    if (videoUrl.match(/youtube\.com|youtu\.be|youtube-nocookie.com/)) {
                        const youtubeRegex = /^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/)|(?:(?:watch)?\?v(?:i)?=|\&v(?:i)?=))([^#\&\?]*).*/;
                        const baseSrc = videoUrl.match(/youtube-nocookie.com/)
                            ? 'https://www.youtube-nocookie.com/embed'
                            : 'https://www.youtube.com/embed';


                        videoData.type = "youtube";
                        videoData.id = videoUrl.match(youtubeRegex)[1];
                        if (this.videoOptions.loop) {
                            videoData.additionalParams += `&playlist=${videoData.id}`
                        }
                        if (this.videoOptions.allowApi) {
                            videoData.additionalParams += '&enablejsapi=1';
                        }
                        videoData.src = `${baseSrc}/${videoData.id}?origin=<?= $block->getBaseUrl() ?>${videoData.additionalParams}`;
                        videoData.allow += "accelerometer; clipboard-write; encrypted-media; gyroscope"
                    } else if (videoUrl.match(/vimeo\.com/)) {
                        const vimeoRegex = new RegExp([
                            'https?:\\/\\/(?:www\\.|player\\.)?vimeo.com\\/(?:channels\\/(?:\\w+\\/)',
                            '?|groups\\/([^\\/]*)\\/videos\\/|album\\/(\\d+)\\/video\\/|video\\/|)(\\d+)(?:$|\\/|\\?)'
                        ].join(''));
                        const timestamp = new Date().getTime();
                        const baseSrc = "https://player.vimeo.com/video";

                        videoData.type = "vimeo";
                        videoData.id = videoUrl.match(vimeoRegex)[3];
                        if (this.videoOptions.allowApi) {
                            videoData.additionalParams += "&api=1"
                        }
                        videoData.src = `${baseSrc}/${videoData.id}?player_id=vimeo${videoData.id}${timestamp}${videoData.additionalParams}`;
                    }

                    return videoData;
                },
                receiveImages(images) {
                    <?php if ($galleryOptionAppendOnReceive):  ?>
                        const initialUrls = this.initialImages.map(image => image.full);
                        const newImages = images.filter(image => !initialUrls.includes(image.full));
                        this.images = [].concat(this.initialImages, newImages);

                        this.$nextTick(() => {
                            this.refreshSlider();
                            this.goToSlide(newImages ? this.initialImages.length : 0);
                        });
                    <?php else: ?>
                        this.images = images;
                        this.$nextTick(() => this.refreshSlider());
                    <?php endif; ?>
                },
                resetGallery() {
                    this.images = this.initialImages;
                    this.$nextTick(() => this.refreshSlider());
                },
                eventListeners: {
                    ['@keydown.window.escape']() {
                        this.fullscreen = false;
                    },
                    ['@update-gallery.window'](event) {
                        this.receiveImages(event.detail);
                    },
                    ['@reset-gallery.window']() {
                        this.resetGallery();
                    },
                },
            }
        }
    </script>
</div>
