<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Catalog\Block\Product\View\Gallery;
use Magento\Catalog\Helper\Image;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Gallery $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, [$block, 'isMainImage']));

if (!empty($images) && empty($mainImage)) {
    $mainImage = reset($images);
}

/** @var Image $helper */
$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

$smallWidth = $block->getImageAttribute('product_page_image_small', 'width', 90);
$smallHeight = $block->getImageAttribute('product_page_image_small', 'height', 90);
$mediumWidth = $block->getImageAttribute('product_page_image_medium', 'width', 700);
$mediumHeight = $block->getImageAttribute('product_page_image_medium', 'height', 700);

$galleryOptionAllowfullscreen = (bool) $block->getVar('gallery/allowfullscreen', 'Magento_Catalog');
$galleryOptionLoop = (bool) $block->getVar('gallery/loop', 'Magento_Catalog');
$galleryOptionArrows = $block->getVar('gallery/arrows', 'Magento_Catalog');
$galleryOptionShowCaption = (bool) $block->getVar('gallery/caption', 'Magento_Catalog');
$galleryOptionShowThumbs = (string) $block->getVar('gallery/nav', 'Magento_Catalog') === 'number';
$galleryOptionShowFullscreenIcon = (bool) $block->getVar('gallery/fullscreenicon', 'Magento_Catalog');
$galleryOptionAppendOnReceive = (string) $block->getVar('gallery_switch_strategy', 'Magento_ConfigurableProduct') === 'append';
$galleryOptionMaxImagesToShow = (int) $block->getVar('gallery/maximages', 'Magento_Catalog') ?: 0;
$galleryOptionColumns = $block->getVar('gallery/columns', 'Magento_Catalog') ?: 1;

$productName = $block->getProduct()->getName();
?>

<div class="w-full pt-6 md:pt-0 md:h-auto md:row-start-1 md:row-span-2 md:col-start-1 md:w-1/2 lg:w-8/12">
    <section
        id="gallery"
        aria-label="<?= $escaper->escapeHtml(__('%1 Gallery', $productName)) ?>"
        x-data="initGallery()"
        x-bind="eventListeners"
    >
        <div
            class="flex md:grid md:grid-cols-1 xl:grid-cols-[repeat(var(--gallery-cols),_minmax(0,_1fr))] gap-2 snap overflow-x-auto overscroll-x-contain md:overflow-visible aspect-[var(--gallery-ratio)] md:aspect-auto <?= $galleryOptionColumns === '1' ? ' max-w-[var(--gallery-width)]' : '' ?>"
            style="
                --gallery-ratio: <?= /* @noEscape */ $mediumWidth . '/' . $mediumHeight ?>;
                --gallery-width: <?= /* @noEscape */ $mediumWidth ?>px;
                --gallery-cols: <?= /* @noEscape */ $galleryOptionColumns ?>"
            x-ref="galleryBody"
            @resize.window.debounce="$nextTick(() => calcIsSlider())"
        >
            <img
                src="<?= /* @noEscape */ $mainImageData ?>"
                alt="<?= $mainImage ? $escaper->escapeHtmlAttr($mainImage->getData('label')) : '' ?>"
                width="<?= /* @noEscape */ $mediumWidth ?>"
                height="<?= /* @noEscape */ $mediumHeight ?>"
                loading="eager"
                :class="'sr-only'"
            >
            <template x-for="(image, index) in images" :key="index">
                <figure
                    class="relative flex flex-col group bg-container-darker w-full shrink-0 snap-start md:snap-align-none"
                    :class="{ 'md:hidden': isImagesToShow((index + 1)) }"
                    x-intersect.full="activeItem = index"
                    :data-active="activeItem === index"
                    :data-show-more-image="`${index > maxImages}`"
                    tabindex="-1"
                >
                    <img
                        width="<?= /* @noEscape */ $mediumWidth ?>"
                        height="<?= /* @noEscape */ $mediumHeight ?>"
                        class="m-auto object-scale-down"
                        :loading="index <= 2 ? 'eager' : 'lazy'"
                        :src="image.img"
                        :alt="image.caption || '<?= $escaper->escapeJs($productName) ?>'"
                    />
                    <?php if (!$galleryOptionAllowfullscreen): ?>
                        <template x-if="activeVideo !== index && image.type === 'video'">
                            <button
                                type="button"
                                class="absolute inset-0"
                                aria-hidden="true"
                                @click="activeVideo = index"
                            >
                                <span class="block m-auto w-max rounded-full transition ease-in text-white bg-primary group-hover:scale-110">
                                    <?= $heroiconsSolid->playHtml('', 38, 38, ['aria-hidden' => 'true']); ?>
                                </span>
                            </button>
                        </template>
                        <template x-if="activeVideo === index && image.type === 'video'">
                            <iframe
                                class="absolute inset-0 aspect-video max-h-full max-w-full"
                                width="1280"
                                height="720"
                                type="text/html"
                                frameborder="0"
                                loading="lazy"
                                x-data="getVideoData(image)"
                                :src="src"
                                :alt="image.caption || '<?= $escaper->escapeJs($productName) ?>'"
                                :title="image.caption || '<?= $escaper->escapeJs($productName) ?>'"
                                :allow="allow"
                            ></iframe>
                        </template>
                    <?php endif; ?>
                    <?php if ($galleryOptionShowCaption): ?>
                        <template x-if="image.caption && image.caption !== '<?= $escaper->escapeJs($productName) ?>'">
                            <figcaption
                                class="absolute inset-x-0 bottom-0 pt-4 pb-2 px-4 text-sm xl:text-base font-bold bg-gradient-to-t from-black/60 text-white text-center
                                md:opacity-0 md:group-hover:opacity-100 transition-opacity"
                                x-text="image.caption"
                            ></figcaption>
                        </template>
                    <?php endif; ?>
                    <?php if ($galleryOptionAllowfullscreen): ?>
                        <button
                            type="button"
                            class="absolute inset-0 outline-offset-4"
                            title="<?= $escaper->escapeHtml(__('Open fullscreen')) ?>"
                            aria-label="<?= $escaper->escapeHtml(__('Open fullscreen')) ?>"
                            data-dialog-toggle
                            x-cloak
                            @click="$dispatch('openGalleryDialog', { content: image })"
                        >
                            <?php if ($galleryOptionShowFullscreenIcon): ?>
                                <template x-if="image.type === 'video'">
                                    <span
                                        class="m-auto w-max block rounded-full transition ease-in text-white bg-primary group-hover:scale-110"
                                        aria-hidden="true"
                                    >
                                        <?= $heroiconsSolid->playHtml('', 38, 38, ['aria-hidden' => 'true']); ?>
                                    </span>
                                </template>
                                <template x-if="image.type !== 'video'">
                                    <span
                                        class="hidden md:block absolute top-2 right-2 md:opacity-0 md:group-hover:opacity-100 transition-opacity"
                                        aria-hidden="true"
                                    >
                                        <span class="block p-1.5 rounded-full transition bg-white/40 text-primary hover:shadow hover:bg-white/80 hover:text-primary">
                                            <?= $heroicons->zoomInHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
                                        </span>
                                    </span>
                                </template>
                            <?php endif; ?>
                        </button>
                    <?php endif; ?>
                </figure>
            </template>
            <template x-if="maxImages !== 0 && (itemCount - 1) > maxImages">
                <button
                    type="button"
                    class="hidden md:flex col-span-full btn justify-center text-base shadow-none bg-slate-200 hover:bg-slate-100 focus:bg-slate-100 text-slate-900"
                    @click="showMoreImages = !showMoreImages"
                >
                    <span x-text="showMoreImages
                        ? '<?= $escaper->escapeHtml(__('View less')) ?>'
                        : '<?= $escaper->escapeHtml(__('View more')) ?>'
                    "
                    ><?= $escaper->escapeHtml(__('View more')) ?></span>
                </button>
            </template>
        </div>
        <?php if ($galleryOptionArrows): ?>
            <nav
                class="flex items-center gap-2 my-4 md:hidden justify-between"
                aria-label="<?= $escaper->escapeHtml(__('%1 Gallery Navigation', $productName)) ?>"
                x-cloak
            >
                <button
                    type="button"
                    tabindex="-1"
                    class="shrink-0 p-2.5 rounded-full transition disabled:opacity-30 shadow hover:shadow-primary/30 focus:shadow-primary/30 bg-white text-primary"
                    title="<?= $escaper->escapeHtml(__('Previous')) ?>"
                    aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
                    :disabled="!loop && isStart"
                    @click="prevItem(); scrollToActive()"
                ><?= $heroiconsSolid->arrowLeftHtml('', 16, 16, ['aria-hidden' => 'true']) ?></button>
                <?php if ($galleryOptionShowThumbs): ?>
                    <div class="font-bold text-sm<?= $galleryOptionArrows === "start"
                        ? ' order-last ml-auto'
                        : ($galleryOptionArrows === "end" ? ' order-first mr-auto' : ' mx-auto') ?>">
                        <span x-text="(activeItem + 1)"></span>
                        <span class="text-gray-300">/</span>
                        <span class="text-gray-500" x-text="itemCount"></span>
                    </div>
                <?php endif; ?>
                <button
                    type="button"
                    tabindex="-1"
                    class="shrink-0 p-2.5 rounded-full transition disabled:opacity-30 shadow hover:shadow-primary/30 focus:shadow-primary/30 bg-white text-primary"
                    title="<?= $escaper->escapeHtml(__('Next')) ?>"
                    aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
                    :disabled="!loop && isEnd"
                    @click="nextItem(); scrollToActive()"
                ><?= $heroiconsSolid->arrowRightHtml('', 16, 16, ['aria-hidden' => 'true']) ?></button>
            </nav>
        <?php endif; ?>
        <?php if ($galleryOptionAllowfullscreen): ?>
            <dialog
                x-data="initGalleryDialog"
                x-bind="dialogListeners"
                class="max-w-full max-h-full bg-transparent p-0 backdrop:bg-black/75 backdrop:backdrop-blur-sm"
            >
                <button
                    class="z-10 fixed top-2 right-2 lg:top-6 lg:right-6 p-1 rounded-full text-white/50 hover:text-white"
                    title="<?= $escaper->escapeHtml(__('Close fullscreen')) ?>"
                    aria-label="<?= $escaper->escapeHtml(__('Close fullscreen')) ?>"
                    @click="closeDialog()"
                >
                    <?= $heroicons->xCircleHtml('', 32, 32, ['aria-hidden' => 'true']); ?>
                </button>
                <div
                    x-show="open"
                    x-transition:enter="transition ease-out duration-300"
                    x-transition:enter-start="opacity-0 translate-y-12"
                    x-transition:enter-end="opacity-100 translate-y-0"
                    x-transition:leave="transition ease-in duration-300"
                    x-transition:leave-start="opacity-100 translate-y-0"
                    x-transition:leave-end="opacity-0 translate-y-12"
                >
                    <template x-if="content && content.type === 'video'">
                        <iframe
                            class="aspect-video max-w-full max-h-screen p-2 sm:p-4 shadow-xl h-auto"
                            width="1280"
                            height="720"
                            type="text/html"
                            frameborder="0"
                            loading="lazy"
                            x-data="getVideoData(content)"
                            :src="src"
                            :alt="content.caption || '<?= $escaper->escapeJs($productName) ?>'"
                            :title="content.caption || '<?= $escaper->escapeJs($productName) ?>'"
                            :allow="allow"
                        ></iframe>
                    </template>
                    <template x-if="content && content.type === 'image'">
                        <img
                            width="<?= /* @noEscape */ $mediumWidth ?>"
                            height="<?= /* @noEscape */ $mediumHeight ?>"
                            class="max-w-full max-h-screen p-2 sm:p-4 shadow-xl w-auto m-auto"
                            :class="{ 'invisible': content.type === 'video' }"
                            loading="lazy"
                            :src="content.full"
                            :alt="content.caption || '<?= $escaper->escapeJs($productName) ?>'"
                        />
                    </template>
                </div>
            </dialog>
        <?php endif; ?>
    </section>
    <script>
        function initGallery() {
            return {
                activeItem: 0,
                activeVideo: false,
                itemCount: 0,
                loop: <?= /* @noEscape */ $galleryOptionLoop ? 'true' : 'false' ?>,
                isSlider: false,
                isStart: true,
                isEnd: false,
                videoOptions: {
                    autoplay: true,
                    loop: false,
                    allowApi: false
                },
                maxImages: <?= /* @noEscape */ $galleryOptionMaxImagesToShow ?>,
                showMoreImages: false,
                initialImages: <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                images: <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                init() {
                    this.itemCount = this.images.length;
                    this.calcIsSlider();

                    this.$watch('activeItem', (item) => {
                        this.isStart = this.activeItem === 0;
                        this.isEnd = this.activeItem === (this.itemCount - 1);
                    });

                    this.$watch('isSlider', (now, previous) => {
                        if (now && now !== previous) {
                            this.activeItem = 0;
                            this.scrollToActive()
                        };
                    });

                    this.$watch('showMoreImages', (isOpen) => {
                        this.$nextTick(() => {
                            const galleryInitItems = this.$refs.galleryBody.querySelectorAll('[data-show-more-image=false]');
                            if (!galleryInitItems.length) return;

                            const galleryItemToScrollTo = galleryInitItems[
                                isOpen
                                    ? galleryInitItems.length - 1 // Go to next item
                                    : galleryInitItems.length - 2 // Go to prev item
                            ]
                            if (!galleryItemToScrollTo) return;

                            galleryItemToScrollTo.scrollIntoView({ behavior: "smooth" });

                            const focusTarget = galleryItemToScrollTo.querySelector('[data-dialog-toggle]');
                            if (focusTarget) {
                                focusTarget.focus();
                            } else {
                                galleryItemToScrollTo.focus();
                            };
                        });
                    })
                },
                isImagesToShow(index) {
                    if (this.maxImages === 0) return false;
                    if (this.showMoreImages) return false;
                    return index > this.maxImages;
                },
                getVideoData(source) {
                    const videoUrl = source.videoUrl;
                    if (!videoUrl) return;

                    const videoData = {
                        id: null,
                        type: null,
                        src: null,
                        additionalParams: "",
                        allow: "fullscreen; picture-in-picture;"
                    }

                    if (this.videoOptions.autoplay) {
                        videoData.additionalParams += '&autoplay=1';
                        videoData.allow += ' autoplay;';
                    }

                    if (this.videoOptions.loop) {
                        videoData.additionalParams += '&loop=1';
                    }

                    if (videoUrl.match(/youtube\.com|youtu\.be|youtube-nocookie.com/)) {
                        const youtubeRegex = /^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/)|(?:(?:watch)?\?v(?:i)?=|\&v(?:i)?=))([^#\&\?]*).*/;
                        const baseSrc = videoUrl.match(/youtube-nocookie.com/)
                            ? 'https://www.youtube-nocookie.com/embed'
                            : 'https://www.youtube.com/embed';

                        videoData.type = "youtube";
                        videoData.id = videoUrl.match(youtubeRegex)[1];
                        if (this.videoOptions.loop) {
                            videoData.additionalParams += `&playlist=${videoData.id}`
                        }
                        if (this.videoOptions.allowApi) {
                            videoData.additionalParams += '&enablejsapi=1';
                        }
                        videoData.src = `${baseSrc}/${videoData.id}?origin=<?= $block->getBaseUrl() ?>${videoData.additionalParams}`;
                        videoData.allow += " accelerometer; clipboard-write; encrypted-media; gyroscope;"
                    } else if (videoUrl.match(/vimeo\.com/)) {
                        const vimeoRegex = new RegExp([
                            'https?:\\/\\/(?:www\\.|player\\.)?vimeo.com\\/(?:channels\\/(?:\\w+\\/)',
                            '?|groups\\/([^\\/]*)\\/videos\\/|album\\/(\\d+)\\/video\\/|video\\/|)(\\d+)(?:$|\\/|\\?)'
                        ].join(''));
                        const timestamp = new Date().getTime();
                        const baseSrc = "https://player.vimeo.com/video";

                        videoData.type = "vimeo";
                        videoData.id = videoUrl.match(vimeoRegex)[3];
                        if (this.videoOptions.allowApi) {
                            videoData.additionalParams += "&api=1"
                        }
                        videoData.src = `${baseSrc}/${videoData.id}?player_id=vimeo${videoData.id}${timestamp}${videoData.additionalParams}`;
                    }

                    return videoData;
                },
                nextItem() {
                    const hasNext = this.activeItem < (this.itemCount - 1);
                    this.activeItem = hasNext
                        ? this.activeItem += 1
                        : this.loop ? 0 : this.activeItem;
                },
                prevItem() {
                    const hasPrev = this.activeItem > 0;
                    this.activeItem = hasPrev
                        ? this.activeItem -= 1
                        : this.loop ? (this.itemCount - 1) : this.activeItem;
                },
                scrollToActive() {
                    this.$nextTick(() => {
                        const activeSlide = this.$refs.galleryBody.querySelector('[data-active]');
                        if (!activeSlide) return;
                        activeSlide.scrollIntoView({ block: "nearest", inline: "nearest" });
                    });
                },
                calcIsSlider() {
                    const overflow = getComputedStyle(this.$refs.galleryBody).overflow;
                    this.isSlider = overflow === "auto" || overflow === "scroll";
                },
                receiveImages(images) {
                    <?php if ($galleryOptionAppendOnReceive):  ?>
                        const initialUrls = this.initialImages.map(image => image.full);
                        const newImages = images.filter(image => !initialUrls.includes(image.full));
                        this.images = [].concat(this.initialImages, newImages);
                    <?php else: ?>
                        this.images = images;
                    <?php endif; ?>
                    this.itemCount = this.images.length;
                },
                resetGallery() {
                    this.images = this.initialImages;
                    this.itemCount = this.images.length;
                },
                eventListeners: {
                    ['@update-gallery.window'](event) {
                        this.receiveImages(event.detail);
                    },
                    ['@reset-gallery.window']() {
                        this.resetGallery();
                    },
                },
            }
        }

        <?php if ($galleryOptionAllowfullscreen): ?>
            function initGalleryDialog() {
                return {
                    open: false,
                    content: null,
                    openDialog(content) {
                        this.$root.showModal();
                        this.open = true;
                        this.content = event.detail.content
                        this.scrollLock(this.open);
                    },
                    closeDialog() {
                        this.$root.close();
                        this.open = false;
                        this.content = null;
                        this.scrollLock(this.open);
                    },
                    scrollLock(use = true) {
                        document.body.style.overflow = use ? "hidden" : "";
                    },
                    onDialogBackdropClickHelper(event, target) {
                        const rect = target.getBoundingClientRect();
                        const isInDialog =
                            rect.top <= event.clientY &&
                            event.clientY <= rect.top + rect.height &&
                            rect.left <= event.clientX &&
                            event.clientX <= rect.left + rect.width;
                        return isInDialog;
                    },
                    dialogListeners: {
                        ['@keydown.window.escape']() {
                            this.closeDialog();
                        },
                        ['@click'](event) {
                            if (this.onDialogBackdropClickHelper(event, this.$root)) return;

                            this.closeDialog();
                        },
                        ['@openGalleryDialog.window'](event) {
                            this.openDialog(event.detail.content);
                        },
                        ['@closeGalleryDialog.window']() {
                            this.closeDialog();
                        }
                    }
                }
            }
        <?php endif; ?>
    </script>
</div>
