<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\ReviewRendererInterface;

/** @var \Magento\Catalog\Block\Product\AbstractProduct $block */
?>
<?= $block->getReviewsSummaryHtml($block->getProduct(), ReviewRendererInterface::FULL_VIEW, true) ?>

