<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/** @var View $block */

$product = $block->getProduct();

?>

<!-- Flixmedia init script -->
<script type= "text/javascript" >
    document.getElementById( "description" ).prepend( "<div id=\"flix-inpage\"></div>" );
    document.getElementById( "description" ).prepend( "<div id=\"flix-minisite\"></div>" );
    
    let product_mpn = "" ,
        product_ean = "<?= $product->getEanCode() ?>" ,
        product_brand = "LEGO" ,
        distributor = "16129" ,
        language = "nl" ;
    
    let headID = document.getElementsByTagName( "head" )[ 0 ];
    let flixScript = document.createElement( 'script' );
    
    flixScript.type = 'text/javascript' ;
    flixScript.async = true ;
    flixScript.setAttribute( 'data-flix-distributor' , distributor);
    flixScript.setAttribute( 'data-flix-language' , language);
    flixScript.setAttribute( 'data-flix-brand' , product_brand);
    flixScript.setAttribute( 'data-flix-ean' , product_ean);
    flixScript.setAttribute( 'data-flix-mpn' , product_mpn);
    flixScript.setAttribute( 'data-flix-inpage' , 'flix-inpage' );
    flixScript.setAttribute( 'data-flix-button' , 'flix-minisite' );
    flixScript.setAttribute( 'data-flix-price' , '' );
    flixScript.setAttribute( 'data-flix-autoload' , 'hotspot' );
    
    headID.appendChild(flixScript);
</script>
<div>test</div>


