<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_PreOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile

/** @var $block \Bss\PreOrder\Block\PreOrderProduct */
?>

<?php $note = $block->getNote(); ?>
<?php foreach ($note as $key) : ?>
    <span class="note-pieces"><?php echo $key ?></span>
<?php endforeach ?>
<span class="order-notice"><?php echo $block->getCartMess() ?></span>
<script type="text/x-magento-init">
    {
        "*": {
            "Bss_PreOrder/js/cart": {}
        }
    }
</script>
