<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_PreOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<input type="hidden" name="group_is_preorder">
<script type="text/x-magento-init">
    {
        "*": {
            "Bss_PreOrder/js/product/group/name-addtocart": {
               "textButton": "<?= /* @escapeNotVerified */ $block->getButtonHtml() ?>"
            }
        }
    }
</script>
