<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_PreOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/** @var $block \Bss\PreOrder\Block\PreOrderProduct */
// @codingStandardsIgnoreFile
?>
<?php
$message = $block->getMessage();
$button = $block->getButtonHtml();
$availabilityMess = $block->getAvailabilityMessage();
?>
<?php if ($block->isGroupProduct()): ?>
    <span class="mess-preorder">
        <a href="#" class="tooltip-toggle"><?= __('Pre Order') ?></a>
        <?php if ($message): ?>
            <span class="tooltip-content"><?= __($message) ?></span>
        <?php else: ?>
            <span class="tooltip-content"><?= __('Available: Pre Order') ?></span>
        <?php endif; ?>
    </span>
    <input type="hidden" name="is_preorder_group_<?= $block->getProduct()->getId(); ?>" value="1">
<?php else :?>
    <div class="bss-pre-order">
        <span class="mess-preorder">
            <a href="#" class="tooltip-toggle"><?= __('Pre Order') ?></a>
            <?php if ($message): ?>
                <span class="tooltip-content"><?= __($message) ?></span>
            <?php else: ?>
                <span class="tooltip-content"><?= __('Available: Pre Order') ?></span>
            <?php endif; ?>
        </span>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Bss_PreOrder/js/index": {
                	<?php if ($availabilityMess): ?>
                		"availability_message" : "<?= $availabilityMess ?>",
                	<?php endif; ?>
                	"buttonText" : "<?= $button; ?>"
            	}
            }
        }
    </script>
<?php endif; ?>
