<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_PreOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/** @var $block \Bss\PreOrder\Block\PreOrderProduct */
// @codingStandardsIgnoreFile
?>
<?php
    $message = $block->getMessage();
    $button = $block->getButtonHtml();
    $availabilityMess = $block->getAvailabilityMessage();
?>
<?php if ($block->isGroupProduct()): ?>
    <span class="mess-preorder"><?= $message ?></span>
    <input type="hidden" name="is_preorder_group_<?= $block->getProduct()->getId(); ?>" value="1">
<?php else :?>
    <div class="bss-pre-order">
        <?php if ($message): ?>
    	   <span class="mess-preorder"><?= $message ?></span>
        <?php endif; ?>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Bss_PreOrder/js/index": {
                	<?php if ($availabilityMess): ?>
                		"availability_message" : "<?= $availabilityMess ?>",
                	<?php endif; ?>
                    <?php if ($block->getProduct()->getExtensionAttributes()->getStockItem()) : ?>
                    "stock_status" : "<?= (int)$block->getProduct()->getExtensionAttributes()->getStockItem()->getIsInStock(); ?>",
                	<?php endif; ?>
                	"buttonText" : "<?= $button; ?>"
            	}
            }
        }
    </script>
<?php endif; ?>
