<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<div x-data="initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?>()"
     class="z-20 order-1 lg:order-2 navigation lg:hidden"
>
    <!-- mobile -->
    <div @load.window="setActiveMenu($root)"
         class="bg-container-lighter"
         :class="{'h-screen overflow-x-hidden overflow-y-auto fixed top-0 left-0 w-full' : open}"
         @toggle-mobile-menu.window="open = !open"
         @keydown.window.escape="open=false"
    >
        <div class="flex items-baseline justify-between menu-icon">
            <div class="flex justify-end w-full">
                <a @click="$dispatch('toggle-mobile-menu')"
                   class="flex items-center justify-center cursor-pointer"
                   :class="{ 'ml-auto': open }">
                    <?= $heroicons->xHtml('hidden p-4', 64, 64, [":class" => "{ 'hidden' : !open, 'block': open }"]); ?>
                    <?= $heroicons->menuHtml('p-3', 48, 48, [":class" => "{ 'hidden' : open, 'block': !open }"]); ?>
                </a>
            </div>
        </div>

        <nav
            class="hidden w-full duration-150 ease-in-out transform border-t transition-display border-container"
            :class="{ 'hidden' : !open }"
        >
            <?php foreach ($menuItems as $index => $menuItem): ?>
                <div class="level-0">
                <span
                    class="flex items-center transition-transform duration-150 ease-in-out transform"
                    :class="{
                        '-translate-x-full' : mobilePanelActiveId,
                        'translate-x-0' : !mobilePanelActiveId
                    }"
                >
                    <a class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                        bg-container-lighter border-container level-0"
                       href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                       title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>">
                        <?= $escaper->escapeHtml($menuItem['name']) ?>
                    </a>
                    <?php if (!empty($menuItem['childData'])): ?>
                        <a class="absolute right-0 flex w-8 h-8 mr-8 border rounded cursor-pointer
                        bg-container-lighter border-container"
                           @click="mobilePanelActiveId =
                          mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>' ?
                           0 : '<?= /* @noEscape */ (string) $index ?>'"
                        >
                        <?= $heroicons->chevronRightHtml('w-full h-full p-1'); ?>
                    </a>
                    <?php endif; ?>
                </span>
                    <?php if (!empty($menuItem['childData'])): ?>
                        <div
                            class="absolute top-0 right-0 z-10 w-full h-full transition-transform duration-200 ease-in-out
                            translate-x-full transform bg-container-lighter"
                            :class="{
                            'translate-x-full' : mobilePanelActiveId !== '<?= /* @noEscape */ (string) $index ?>',
                            'translate-x-0' : mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>',
                        }"
                        >
                            <a class="flex items-center px-8 py-4 border-b cursor-pointer bg-container border-container"
                               @click="mobilePanelActiveId = 0"
                            >
                                <?= $heroicons->chevronLeftHtml(); ?>
                                <span class="ml-4">
                                <?= $escaper->escapeHtml($menuItem['name']) ?>
                            </span>
                            </a>
                            <a href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                               title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                               class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                            bg-container-lighter border-container"
                            >
                                <span class="w-6"></span>
                                <span class="ml-4"><?= $escaper->escapeHtml(__('View All')) ?></span></a>
                            <?php foreach ($menuItem['childData'] as $subMenuItem): ?>

                                <a href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                                   title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                                   class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                bg-container-lighter border-container"
                                >
                                    <span class="w-6"></span>
                                    <span class="ml-4 text-base text-gray-700 lg:ml-0">
                                    <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                </span>
                                </a>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </nav>
    </div>
</div>
<script>
    'use strict';

    const initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            mobilePanelActiveId: null,
            open: false,
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item.classList.add('underline');
                    item.closest('div.level-0') &&
                    item.closest('div.level-0').querySelector('a.level-0').classList.add('underline');
                });
            }
        }
    }
</script>
