<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_PreOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php
/** @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder();
/** @var \Bss\PreOrder\Helper\Data $preOrderHelper */
$preOrderHelper = $this->helper('Bss\PreOrder\Helper\Data');
$notePreOrder = $preOrderHelper->getNote();
?>
<?php if ($_order) : ?>
    <?php
        $_items = $_order->getAllItems();
        $listPreOrder = $_order->getProductPreOrder();
        if ($listPreOrder) {
            $listPreOrder = $preOrderHelper->serializeClass()->unserialize($listPreOrder);
            $listPreOrder = array_keys($listPreOrder);
        } else {
            $listPreOrder = [];
        }
    ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= $block->escapeHtml(__('Items')) ?>
            </th>
            <th class="item-qty">
                <?= $block->escapeHtml(__('Qty')) ?>
            </th>
            <th class="item-price">
                <?= $block->escapeHtml(__('Price')) ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($_items as $_item) : ?>
            <?php if (!$_item->getParentItem()) : ?>
                <tbody>
                <?= $block->getItemHtml($_item) ?>
                <?php $productModel = $_item->getProduct();
                if ($_item->getProductType() == 'configurable') {
                    $productModel = $preOrderHelper->getProductBySku($_item->getProductOptionByCode('simple_sku'));
                }
                ?>
                <?php if ($productModel && in_array($productModel->getId(), $listPreOrder)): ?>
                <tr>
                    <td>
                        <p><?= $notePreOrder ?></p>
                        <p><?= $preOrderHelper->getAvailabilityMessage($productModel) ?></p>
                    </td>
                    <td></td>
                    <td></td>
                </tr>
                <?php endif; ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
        <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->isMessagesAllowed('order', $_order, $_order->getStore())
        && $_order->getGiftMessageId()
    ) : ?>
        <?php $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage) : ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message for this Order')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
