<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\GraphqlViewModel\ViewModel\GraphqlViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\Store;
use Magento\Framework\Escaper;
use Magento\Review\Block\Form;
use Hyva\Theme\ViewModel\ReCaptcha;

//phpcs:disable Generic.Files.LineLength

/** @var Escaper $escaper */
/** @var Form $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

$formId = 'review_form';

/** @var GraphqlViewModel $gqlViewModel */
$gqlViewModel = $viewModels->require(GraphqlViewModel::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on Magento_ReCaptchaReview module
/** @var ReCaptcha $recaptcha */
$recaptcha = $block->getData('viewModelRecaptcha');

?>
<div x-data="{open: false}">
    <!-- button -->    
    <button @click = "open = true" class="bg-lego-blue-dark text-white rounded-[2rem] block mx-auto py-4 px-16">
        <?= $escaper->escapeHtml(__('Write Your Own Review')) ?>
    </button>
    <!-- Modal -->
    <div x-show = "open" x-transition
         style = "display:none"
         @keydown.escape.prevent.stop = "open = false"
         role = "dialog"
         aria-modal = "true"
         x-id = "['modal-review-form']"
         :aria-labelled-by = "$id('modal-review-form')"
         class = "fixed inset-0 z-10 overflow-y-auto" >

        <!-- overlay -->
        <div class="fixed inset-0 bg-black bg-opacity-70"></div>

        <!-- panel -->
        <div 
            @click = "open = false"
            class= "relative h-full w-full items-center justify-center flex mx-2 md:mx-0 rounded-sm">
            <div 
                @click.stop
                class="max-w-screen-xl w-full bg-white border border-gray-900 p-4 overflow-y-auto">
                <!-- title -->
                <h2 class="text-2xl font-semibold"><?= $escaper->escapeHtml(__('Write Your Own Review')) ?></h2>
                <!-- content -->
                <span>Hier komt het formulier</span>
            </div>
        </div>
    </div>
</div>