<?php
/**
 * @author    JaJuMa GmbH <info@jajuma.de>
 * @copyright Copyright (c) 2021 JaJuMa GmbH <https://www.jajuma.de>. All rights reserved.
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */

declare(strict_types=1);

/** @var $block \Hyva\JajumaImageOptimizerUltimate\Block\Picture */
$originalTag = $block->getOriginalTag();

$originalSrc = $block->getOriginalImage();

$srcsetTag = $block->getCustomSrcSetTag() ? $block->getCustomSrcSetTag() : "srcset";

$isLazyLoadEnabled = $block->isNativeLazyLoadingEnabled();
$excludeNativeLazyloadImageAttributes = $block->getExcludeNativeLazyloadImageAttributes();
$isImageInExcludeList = preg_match_all($excludeNativeLazyloadImageAttributes, $originalTag);

/**
 * Need to hard code srcset for each case here
 * Because there is no rule for :srcset binding
 * Here we handle common cases on Hyva: Slider, Product Gallery main and thumb
 */

$webpSrcset = $avifSrcset = false;

if ($isLazyLoadEnabled && !$isImageInExcludeList) {
    // add loading="lazy" at the end of the img tag
    if (substr($originalTag, -2) === '/>') {
        // replace "/>" with " loading="lazy" />"
        $originalTag = preg_replace('/\/>$/', ' loading="lazy" />', $originalTag);
    } elseif (substr($originalTag, -1) === '>') {
        // replace ">" with " loading="lazy" >"
        $originalTag = preg_replace('/>$/', ' loading="lazy" >', $originalTag);
    }
}


if(strpos($originalSrc, 'small_image') !== false && strpos($originalSrc, 'item') === false) {
    //Slider Images
    $webpSrcset = "product.small_image.url_webp !== 'false' ? product.small_image.url_webp : ''";
    $avifSrcset = "product.small_image.url_avif !== 'false' ? product.small_image.url_avif : ''";
    $originSrcHighres = $originalSrc;
}

if(strpos($originalSrc, 'fullscreen') !== false) {
    //Gallery Images
    $webpSrcset = "fullscreen ? image.full_webp : image.img_webp";
    $avifSrcset = "fullscreen ? image.full_avif : image.img_avif";
    $originSrcHighres = $originalSrc;
}

if(strpos($originalSrc, 'thumb') !== false) {
    //Gallery Thumbs
    $webpSrcset = "image.thumb_webp";
    $avifSrcset = "image.thumb_avif";
    $originSrcHighres = "image.thumb_highres";
}

if($originalSrc == 'fullscreen ? image.full : image.img')
    $originSrcHighres = 'fullscreen ? image.full_highres : image.img_highres'
?>




<?php if($webpSrcset && $avifSrcset): ?>
<picture>
    <?php if($block->isAvifEnabled()): ?>
    <source type="image/avif" :<?= /* @noEscape */ $srcsetTag?>="<?= /* @noEscape */ $avifSrcset?>">
    <?php endif ?>
    <source type="image/webp" :<?= /* @noEscape */ $srcsetTag?>="<?= /* @noEscape */ $webpSrcset?>">
    <?php if($block->isHighResolutionEnabled()): ?>
    <source type="" :<?= /* @noEscape */ $srcsetTag?>="<?= /* @noEscape */ $originSrcHighres ?>">
    <?php else: ?>
    <source type="" :<?= /* @noEscape */ $srcsetTag?>="<?= /* @noEscape */ $originalSrc ?>">
    <?php endif ?>
    <?= /* @noEscape */ $originalTag ?>
</picture>
<?php else: ?>
    <?= /* @noEscape */ $originalTag ?>
<?php endif ?>
