<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div class="bg-blue-900 text-white text-sm leading-5 font-semibold text-center p-2">
    <a href="#" class="hover:underline">
        <?= $escaper->escapeHtml(__('Get ready for a dazzling summer with our new arrivals')) ?>
        <?= $heroicons->chevronRightHtml(
            'inline-block align-text-bottom text-blue-300',
            16,
            16,
            ['aria-hidden' => 'true', 'stroke-width' => '4']
        ); ?>
    </a>
</div>
