<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div
    x-data = "{}"
    x-init = "$nextTick(() => {
        if (screen.width < 769) {
            let ul = $refs.usps;
            ul.insertAdjacentHTML('afterend', ul.outerHTML);
            ul.nextSibling.setAttribute('aria-hidden', 'true');
        }

    })"
    class="px-4 py-2 bg-lego-blue-lighter text-center inline-flex overflow-hidden gap-11 w-full flex-nowrap">
    <ul x-ref="usps" class="sm:container flex justify-center gap-11 lg:justify-between text-gray-700 animate-infinite-scroll sm:animate-none">
        <li class="flex flex-nowrap items-center gap-3">
            <?= $heroicons->clockHtml('text-lego-blue-light',24,24) ?>
            <span class="whitespace-nowrap">Vandaag voor 21:30 besteld, <strong>morgen in huis!</strong></span>
        </li>
        <li class="flex flex-nowrap items-center gap-3">
            <?= $heroicons->truckHtml('text-lego-blue-light',24,24) ?>
            <span class="whitespace-nowrap"><strong>Gratis verzending</strong> vanaf 99,-</span>
        </li>
        <li class="flex flex-nowrap items-center gap-3">
            <?= $heroicons->badgeCheckHtml('text-lego-blue-light',24,24) ?>
            <span class="whitespace-nowrap">Kiyoh klantwaardering: <strong>9.5</strong></span>
        </li>
    </ul>
</div>
