<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div class="px-4 py-2 bg-lego-blue-lighter text-center">
    <ul class="container flex justify-center gap-11 lg:justify-between text-gray-700 animate-infinite-scroll sm:animate-none">
        <li class="lg:flex items-center gap-3">
            <?= $heroicons->clockHtml('text-lego-blue-light') ?>
            <span>Vandaag voor 21:30 besteld, <strong>morgen in huis!</strong></span>
        </li>
        <li class="lg:flex items-center gap-3">
            <?= $heroicons->truckHtml('text-lego-blue-light') ?>
            <span>Gratis verzending vanaf 99,-</span>
        </li>
        <li class="lg:flex items-center gap-3">
            <?= $heroicons->badgeCheckHtml('text-lego-blue-light') ?>
            <span>Kiyoh klantwaardering van 9.5</span>
        </li>
    </ul>
</div>
