<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Framework\Escaper;
use Magento\Review\Block\Product\View as ProductReview;
use Magento\Theme\Block\Html\Pager;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var ProductReview $block */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaper */
/** @var Pager $toolbar */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$reviewCollection = $block->getReviewsCollection();

// Note: Setting the collection on the toolbar block applies pagination, so it has to happen before collection loading.
if ($toolbar = $block->getChildBlock('review_list.toolbar')) {
    $toolbar->setCollection($reviewCollection);
}
$reviewCollection->load()->addRateVotes();
$items = $reviewCollection->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($items)): ?>
    <div class="mx-auto py-6 items-center" id="customer-review-list" x-data="{collapsed: true}">
        <div class="container mx-auto flex py-6 mb-6 md:flex-row border-y-[1px] border-gray-200 bg-gray-100 px-4">
            <?php if (!$block->getHideTitle()): ?>
                <h3 class="text-gray-900 text-lg md:text-2xl text-center md:text-left uppercase flex flex-row justify-between w-full font-semibold">
                    <?= $escaper->escapeHtml(__('Customer Reviews')) ?>
                </h3>
            <?php endif ?>
                <svg x-show="collapsed" @click="collapsed = !collapsed" xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 opacity-90 -mr-2 md:mr-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <svg x-show="!collapsed" @click="collapsed = !collapsed" xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 opacity-90 -mr-2 md:mr-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
        </div>
        <div class="card w-full px-6 py-3" x-show="!collapsed">
            <?php foreach ($items as $review): ?>
                <div itemscope itemprop="review" itemtype="http://schema.org/Review"
                    class="border-b pb-4 my-4 border-container last:border-0 last:mb-0">
                    <?php if (count($review->getRatingVotes())): ?>
                        <div class="table">
                        <?php foreach ($review->getRatingVotes() as $vote): ?>
                            <?php
                                $rating = $vote->getPercent();
                                $ratingSteps = 5;
                                $starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
                                $starsEmpty = floor($ratingSteps - $starsFilled);
                            ?>
                            <div class="table-row" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                <div class="table-cell pr-6 align-middle text-left">
                                    <?= $escaper->escapeHtml($vote->getRatingCode()) ?>
                                </div>
                                <span class="hidden" itemprop="ratingValue"><?= /** @noEscape */ $starsFilled; ?></span>
                                <div class="flex flex-row">
                                    <?php $i = 0; ?>
                                    <?php while ($i < $starsFilled): ?>
                                        <?= $heroiconsSolid->starHtml('text-yellow-400'); ?>
                                        <?php $i++; ?>
                                    <?php endwhile; ?>
                                    <?php $i = 0; ?>
                                    <?php while ($i < $starsEmpty): ?>
                                        <?= $heroiconsSolid->starHtml('text-gray-400'); ?>
                                        <?php $i++; ?>
                                    <?php endwhile; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <div class="text-lg my-2" itemprop="name">
                        <?= $escaper->escapeHtml($review->getTitle()) ?>
                    </div>
                    <div>
                        <span><?= $escaper->escapeHtml(__('Review by')) ?></span>
                        <strong itemprop="author"><?= $escaper->escapeHtml($review->getNickname()) ?></strong>
                        <span class="text-gray-700 inline-block ml-2">
                            <time
                                itemprop="datePublished"
                                datetime="
                                <?= $escaper->escapeHtmlAttr(
                                    $block->formatDate(
                                        $review->getCreatedAt(),
                                        $format
                                    )
                                ); ?>">
                                <?= $escaper->escapeHtml(
                                    $block->formatDate($review->getCreatedAt(), $format)
                                ) ?>
                            </time>
                        </span>
                    </div>
                    <div class="mt-2" itemprop="description">
                        <?= /* @noEscape */ nl2br($escaper->escapeHtml($review->getDetail())) ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php if ($toolbar): ?>
        <div class="toolbar review-toolbar mt-4" x-show="!collapsed">
            <?= $toolbar->toHtml() ?>
        </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
