<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);
/** @var Product $product */
$product = $productViewModel->getProduct();
$productType = $product->getTypeId();

?>
<div class="w-full mb-6 order-3 md:col-start-2 md:row-start-2">
    <?php
    /**
     * Removed #5 https://github.com/bfound2016/mrbricks3_hyva/issues/5
     */
    ?>

    <?php
    /**
    * #8 Removed product details (attributes)
    */
    ?>

    <?= $block->getChildHtml('product.info.form') ?>

    <div class="flex flex-col items-start my-4">

        <?php if ($productType === 'bundle'): ?>
            <span class="sr-only">
                <?= $escaper->escapeHtml(__('The price depends on the chosen options')) ?>
            </span>
        <?php endif; ?>

        <div role="group" class= "w-full md:order-2" aria-label="<?= $escaper->escapeHtmlAttr('Price') ?>">
            <?= $block->getChildHtml("product.info.price") ?>
        </div>
        <?php /** #10 Moved short description here 8 */ ?>
        <?php if ($shortDescription = $productViewModel->getShortDescription()) { ?>
            <div class="md:block my-4 leading-relaxed product-description prose md:order-1"><?= /* @noEscape */ $shortDescription ?></div>
        <?php } ?>

        <div class="flex  flex-col gap-4 w-full mt-4 mr-auto sm:mt-0">
            <?php if ($product->isSaleable()): ?>
                <?= $block->getChildHtml("product.info.quantity") ?>
                <?= $block->getChildHtml("product.info.addtocart") ?>
            <?php endif; ?>
        </div>

    </div>
    <?php /** #8 Moved beneath price */ ?>
    <div class="flex flex-col sm:flex-row justify-between my-4 md:order-3">
        <?= $block->getChildHtml("product.info.stockstatus") ?>
        <?= $block->getChildHtml("alert.urls") ?>
    </div>

    <?php
        /**
         * #8 Removed share / wishlist / mailtofriend
         */
    ?>

    <?= $block->getChildHtml("product.info.additional") ?>
</div>
