<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);

/** @var Product $product */
$product        = $productViewModel->getProduct();
$productType    = $product->getTypeId();

$categoriesData = $productViewModel->getCategoriesData($product);
?>
<div class="hidden md:flex md:flex-row md:justify-end md:gap-4 md:col-start-2 md:row-start-1">
    <?php foreach ($categoriesData as $categoryData): ?>
        <?php
            if ($categoryData['category_logo'] == null) continue;

            $baseMediaDir = $productViewModel->getBaseMediaDir();

            /**
             * Method to get image dimensions
             * @var $imagepath string
             */
            $imagepath = $baseMediaDir . $categoryData['category_logo'];
            list ($width, $height) = getimagesize($imagepath);
        ?>

        <a class="flex flex-col justify-center" href="<?= $escaper->escapeUrl($productViewModel->getCategoryUrl($categoryData["id"])) ?>" target="_self" aria-label="Logo link for <?= $escaper->escapeHtmlAttr($categoryData['name']) ?> theme">
            <img id="category_logo"
                 src="<?= $productViewModel->getStoreUrl() . $categoryData['category_logo']?>"
                 alt="Logo <?= $categoryData['name']?> thema" aria-labelledby="Logo <?= $categoryData['name']?> thema"
                 width="<?= $width/2?>"
                 height="<?= $height/2;?>"
                 loading="lazy"
            />
        </a>
        <?php break; ?>
    <?php endforeach; ?>
</div>
<div class="w-full mb-6 order-3 md:col-start-2 md:row-start-2">
    <?php
    /**
     * Removed #5 https://github.com/bfound2016/mrbricks3_hyva/issues/5
     */
    ?>

    <?php
    /**
    * #8 Removed product details (attributes)
    */
    ?>

    <?= $block->getChildHtml('product.info.form') ?>

    <div class="flex flex-col items-start my-4 md:my-0">

        <?php if ($productType === 'bundle'): ?>
            <span class="sr-only">
                <?= $escaper->escapeHtml(__('The price depends on the chosen options')) ?>
            </span>
        <?php endif; ?>

        <div role="group" class= "w-full md:order-2" aria-label="<?= $escaper->escapeHtmlAttr('Price') ?>">
            <?= $block->getChildHtml("product.info.price") ?>
        </div>
        <?php /** #10 Moved short description here 8 */ ?>
        <?php if ($shortDescription = $productViewModel->getShortDescription()) { ?>
            <div class="md:block my-4 md:my-0 md:mb-4 leading-relaxed product-description prose md:order-1"><?= /* @noEscape */ $shortDescription ?></div>
        <?php } ?>

        <div class="flex flex-col gap-4 w-full mt-4 mr-auto md:order-3">
            <?php if ($product->isSaleable()): ?>
                <?php /*
                <?= $block->getChildHtml("product.info.quantity") ?>
                */ ?>
                <?= $block->getChildHtml("product.info.stockstatus") ?>
                <?= $block->getChildHtml("product.info.addtocart") ?>
            <?php endif; ?>
        </div>

    </div>
    <?php /** #8 Moved beneath price */ ?>
    <div class="flex flex-col justify-between my-4 border-lego-blue-lighter">
        <?= $block->getChildHtml("product.info.selling.points") ?>
        <?= $block->getChildHtml("alert.urls") ?>
    </div>

    <?php
        /**
         * #8 Removed share / wishlist / mailtofriend
         */
    ?>

    <?= $block->getChildHtml("product.info.additional") ?>
</div>
