<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/** @var View $block */

$product = $block->getProduct();
?>
<script>
    window.addEventListener('DOMContentLoaded', function ()
        {
            LEGO.loadPdp(
                'lego-pdp-container',
                '10279',
                'nl-NL,en-US',
                'niQtL0NscK7h46I0HRNiP38qQ8VJrc5yaaJ4vU48')
        }
    )

</script>
<div id="lg-pdp-cntnr"></div>