<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/** @var View $block */

$product = $block->getProduct();
?>
<div id="lg-pdp-cntnr" x-intersect="initPDP()" ></div>
<script type="text/javascript">
        function initPDP() {
            LEGO.loadPdp(
                'lg-pdp-cntnr',
                '10300',
                'nl-NL,en-US',
                'M18aMbb5My1Mt5hpV7DlX8qMmdUyvqBl8guMoTji'
            );
        }
</script>
