<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/** @var View $block */

$product = $block->getProduct();
?>
<script type="text/javascript">
    function checkLEGO() {
        if (LEGO == undefined) {
            window.setTimeout(checkLEGO(),500);
        }
        else {
            initPDP();
        }
    }
    function initPDP() {
        /*
        LEGO.loadPdp(
            'lg-pdp-cntnr',
            '<?= $product->getSku() ?>',
            'nl-NL,en-US',
            'M18aMbb5My1Mt5hpV7DlX8qMmdUyvqBl8guMoTji'
        );*/
    }
</script>
<div id="lg-pdp-cntnr" x-data="{}" x-init="checkLEGO()"></div>
