<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/** @var View $block */

$product = $block->getProduct();

?>
<!-- Flixmedia init script -->
<script type="text/javascript">
    function initPDP() {
        LEGO.loadPdp(
            'lg-pdp-cntnr',
            '<?= $product->getSku() ?>',
            'nl-NL,en-US',
            'M18aMbb5My1Mt5hpV7DlX8qMmdUyvqBl8guMoTji'
        );
    }

    window.addEventListener('init-external-scripts', () => {
        let headID = document .getElementsByTagName( "head" )[ 0 ];
        let pdpScript = document .createElement( 'script' );

        pdpScript.type = 'text/javascript' ;
        pdpScript.async = true ;

        pdpScript.src = '//image.content.lego.com/public/download/pdp/scripts/pdp.js';
        pdpScript.id = 'lgpdp'
        headID.appendChild(pdpScript);

        document.querySelector('#lgpdp').addEventListener('load', window.setTimeout(initPDP(),500));
    },{once: true, passive: true})
</script>
