<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/** @var View $block */

$product = $block->getProduct();

?>
<!-- Flixmedia init script -->
<script type="text/javascript">
        let headID = document .getElementsByTagName( "head" )[ 0 ];
        let pdpScript = document .createElement( 'script' );

        pdpScript.type = 'text/javascript' ;
        pdpScript.async = true ;

        pdpScript.src = '//image.content.lego.com/public/download/pdp/scripts/pdp.js';
        headID.appendChild(pdpScript);
</script>
