<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/**
 * @var View $block
 * @var ViewModelRegistry $viewModels
 */

$product = $block->getProduct();
$heroiconsOutline = $viewModels->require(HeroiconsOutline::class);
?>
<div class="selling-points">
    <ol>
        <li><?= $heroiconsOutline->checkHtml("text-lego-blue-light mr-2 inline",16,16) ?><span>Onze klanten waarderen ons met een <strong>9.5</strong>.</span></li>
        <li><?= $heroiconsOutline->checkHtml("text-lego-blue-light mr-2 inline",16,16) ?><span>Bezorgd voor <strong>4,95</strong>. <strong>Gratis verzending</strong> vanaf <strong>99,-</strong></li>
        <li><?= $heroiconsOutline->checkHtml("text-lego-blue-light mr-2 inline",16,16) ?><span><strong>Eenvoudig</strong> en <strong>veilig</strong> betalen</span></li>
        <li><?= $heroiconsOutline->checkHtml("text-lego-blue-light mr-2 inline",16,16) ?><span>Bezorging <strong>waar</strong> en <strong>wanneer</strong> u wilt!</span></li>
    </ol>
</div>
