<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/**
 * @var View $block
 * @var ViewModelRegistry $viewModels
 */

$product = $block->getProduct();
$heroiconsOutline = $viewModels->require(HeroiconsOutline::class);
?>
<div class="selling-points">
    <ol>
        <li><?= $heroiconsOutline->checkHtml("text-lego-blue-light mr-2 inline",16,16) ?><span>Bezorging 5,95 <strong>Gratis vanaf 99,-</strong></li>
        <li><?= $heroiconsOutline->checkHtml("text-lego-blue-light mr-2 inline",16,16) ?>Bezorgd waar en wanneer je wilt</li>
        <li><?= $heroiconsOutline->checkHtml("text-lego-blue-light mr-2 inline",16,16) ?><span>Gemakkelijk en <strong>veilig betalen</strong></li>
        <li><?= $heroiconsOutline->checkHtml("text-lego-blue-light mr-2 inline",16,16) ?><span>Onze Kiyoh klantwaardering is <a href="https://www.kiyoh.com/reviews/1047517/mister_bricks?lang=nl" target="_blank" aria-labelledby="Kiyoh klantwaardering"><strong>9.5</strong></a></span></li>
    </ol>
</div>
