<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/** @var View $block */

$product = $block->getProduct();

?>
<div class="flex flex-col justify-center my-4 p-4 bg-lego-blue-lighter border-lego-blue-lighter text-sm">
    <ol>
        <li>Onze klanten waarderen ons met <span class="text-lego-blue-light title-font">9.5</span></li>
        <li>Verzending vanaf 4,95. <span class="text-lego-blue-light title-font">Gratis verzending vanaf 99,-</span></li>
        <li><span class="text-lego-blue-light title-font">Eenvoudig en veilig</span> betalen</li>
        <li>Bezorging waar en wanneer u wilt!</li>
    </ol>
</div>
