<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;

/** @var View $block */
/** @var ViewModelRegistry $viewModels */

$product = $block->getProduct();
$productViewModel = $viewModels->require(ProductPage::class);
$baseUrl = $productViewModel->getBaseUrl();
?>
<script>
    function setPageBackground() {
        if (!window.matchMedia("(max-width: 767px)").matches) {
            var productCategories   = <?= json_encode($productViewModel->getCategoriesData($product)) ?>;
            var categoryBackground  = productCategories.find(function(category) {
                return category.category_background !== null;
            });

            if (categoryBackground) {
                let img = new Image();
                img.src = '<?= $baseUrl ?>' + categoryBackground.category_background;
                img.onload = function() {
                    document.body.style.backgroundImage = 'url(' + '<?= $baseUrl ?>' + categoryBackground.category_background + ')';
                    document.body.style.backgroundSize = "'"+ img.width + "px " + img.height + "px'";
                    document.body.style.backgroundPosition = 'center top';
                    document.body.style.backgroundRepeat = 'no-repeat';
                    document.body.style.backgroundAttachment = 'fixed';
                }
            }
            console.log("I'm on a non-mobile device");
        }
    }
</script>
<section x-data={} x-init="setPageBackground()" class="text-gray-700 body-font">
    <div class="flex pb-6 md:py-6 lg:flex-row flex-col items-center">
        <div class="grid grid-rows-auto grid-cols-1 md:gap-x-5 md:grid-cols-[42%_minmax(0,_1fr)] md:grid-rows-[min-content_minmax(0,_1fr)] lg:gap-x-20 lg:grid-cols-[60%_minmax(0,_1fr)] w-full">
            <?= $block->getChildHtml('product.title') ?>
            <?= $block->getChildHtml('product.media') ?>
            <?= $block->getChildHtml('product.info') ?>
        </div>
    </div>
</section>
<section>
    <?= $block->getChildHtml('product_options_wrapper_bottom') ?>
</section>
<!--<div id="hr-recom-k6644d6a0ab416f68bff69f76" ></div>-->
<?= $block->getChildHtml('recommendations-slider') ?>
<?= $block->getChildHtml('product.rich.media'); ?>
<?= $block->getChildHtml('product.info.details'); ?>

<section>
    <?= $block->getChildHtml('related') ?>
    <?= $block->getChildHtml('upsell') ?>
    <?= $block->getChildHtml('review_list') ?>
    <?= $block->getChildHtml('review_form') ?>
</section>
