<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);


/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Framework\Escaper;

$productViewModel = $viewModels->require(ProductPage::class);
$product = $productViewModel->getProduct();

?>
<div class="container mx-auto flex py-6 mb-6 md:flex-row border-y-[1px] border-gray-200 bg-gray-100 px-0">
    <h2 class="text-gray-900 text-lg md:text-2xl title-font font-base text-center md:text-left w-full uppercase px-4 flex flex-row justify-between">
    <span class="font-semibold whitespace-nowrap overflow-clip text-ellipsis"><?= $escaper->escapeHtml($product->getName()) ?> <?= $sectionBlock->getTitle() ? $escaper->escapeHtml($sectionBlock->getTitle()) : '&nbsp;' ?></span>
    </h2>
</div>
