<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Framework\Escaper;

$productViewModel = $viewModels->require(ProductPage::class);
$product = $productViewModel->getProduct();

?>
<div class="container mx-auto flex py-6 mb-6 md:flex-row border-y-[1px] border-gray-200 bg-gray-100 px-0" @x-data="{expanded-1: true}">
    <h2 class="text-gray-900 text-lg md:text-2xl title-font font-base text-center md:text-left w-full uppercase px-4 flex flex-row justify-between">
        <span class="font-semibold whitespace-nowrap overflow-clip text-ellipsis"><?= $escaper->escapeHtml($product->getName()) ?> <?= $escaper->escapeHtml(__('Description')) ?></span>
        <svg x-show="expanded-1" xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 opacity-90 -mr-2 md:mr-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 opacity-90 -mr-2 md:mr-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
    </h2>
</div>