<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Framework\Escaper;

$productViewModel = $viewModels->require(ProductPage::class);
$product = $productViewModel->getProduct();

?>
<div class="container mx-auto flex pt-6 pb-3 mb-6 md:flex-row border-b-2 border-gray-300">
    <h2 class="text-gray-900 text-2xl title-font font-base text-center md:text-left w-full">
        <?= $escaper->escapeHtml(__('Description')) ?> /
        <span class="font-semibold"><?= $escaper->escapeHtml($product->getName()) ?></span>
    </h2>
</div>
