<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Framework\Escaper;

$productViewModel = $viewModels->require(ProductPage::class);
$product = $productViewModel->getProduct();

?>
<div class="container mx-auto flex py-6 mb-6 md:flex-row border-y-[1px] border-gray-100 px-0">
    <h2 class="text-gray-900 text-2xl title-font font-base text-center md:text-left w-full uppercase whitespace-nowrap overflow-clip text-ellipsis">
        <span class="font-semibold"><?= $escaper->escapeHtml($product->getName()) ?> <?= $escaper->escapeHtml(__('Description')) ?></span>
        <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
        </svg>
    </h2>
</div>
