<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Hyva_BssPreOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\BssPreOrder\ViewModels\Helper as ModuleViewModel;
use Bss\PreOrder\Helper\Data as BssPreOder;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var BssPreOder $preOrderHelper */
/** @var CurrentProduct $currentProduct */
$currentProduct     = $viewModels->require(CurrentProduct::class);
$moduleViewModel    = $viewModels->require(ModuleViewModel::class);
$preOrderHelper     = $moduleViewModel->getHelper();

/** @var Product $product */
$product            = $currentProduct->get();
$currentProductId   = $product->getId();

if (!$currentProductId) {
    return;
}

$availabilityMess   = $preOrderHelper->getMess();
$isPreOder          = $preOrderHelper->isPreOrder($preOrderHelper->getPreOrder($currentProductId),$preOrderHelper->getIsInStock($currentProductId));
$inStock            = $product->getIsSalable();
?>
<script>
    function getAvailabilityData() {
        return {
            isStockStatus: true,
            checkStockStatus(productId) {
               for (const [key, val] of Object.entries(this.allProductChild.child)) {
                   if(val.productId === productId) {
                       return val.stock_status;
                   }
               }
            },
            getDayOfTheWeek(delay) {
                if (delay === 0 || delay === undefined) {
                    return "morgen";
                }
                let days = ['zondag', 'maandag', 'dinsdag', 'woensdag', 'donderdag', 'vrijdag', 'zaterdag'];
                let date = new Date();
                date.setDate(date.getDate() + 1 + delay);
                let dayOfWeek = date.getDay();
                if (dayOfWeek === 0 || dayOfWeek === 6) {
                    dayOfWeek = 2; // Set to 'dinsdag' if the day of ordering is Sunday or Saturday
                }
                return days[dayOfWeek];
            }


        }
    }
</script>
<div x-data="getAvailabilityData()">
    <?php if ($preOrderHelper->getIsInStock($currentProductId) && !$isPreOder): ?>
        <div class="stock available flex flex-col available stock p-4 border-lego-blue-lighter border"
             title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
            <div class="flex gap-x-2 items-center">
                <span class="w-3 h-3 text-lego-green bg-lego-green rounded-full flex-shrink-0"></span>
                <span class="font-semibold text-lego-green"><?= $escaper->escapeHtml($inStock ? __('In stock') : __('Out of stock')) ?></span>
                <span class="block">Nu besteld = <span x-text="getDayOfTheWeek(0)">morgen</span> in huis</span>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($availabilityMess && $isPreOder): ?>
        <span class="availability_message"><?= $preOrderHelper->replaceVariableX($availabilityMess, $preOrderHelper->formatDate($product->getData('restock'),IntlDateFormatter::SHORT,false,'Europe/Amsterdam')) ?></span>
    <?php endif; ?>
</div>
