<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Checkout\Block\Cart\Sidebar as SidebarCart;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
$showMiniCart = $storeConfig->getStoreConfig(SidebarCart::XML_PATH_CHECKOUT_SIDEBAR_DISPLAY);
?>
<script>
    function initHeader () {
        return {
            searchOpen: false,
            cart: {},
            isCartOpen: false,
            isMobile: true,
            init() {
                this.checkIsSearchMobile();
            },
            getData(data) {
                if (data.cart) { this.cart = data.cart }
            },
            isCartEmpty() {
                return !this.cart.summary_count
            },
            checkIsSearchMobile() {
                const mobileElement = this.$refs.searchContainerMobile;
                this.isMobile = mobileElement
                    ? getComputedStyle(mobileElement).display !== "none"
                    : window.matchMedia('(max-width: 1023px)').matches; // Fallback to `md` breakpoint

                if (this.isMobile){
                    this.$refs.searchContainerMobile.appendChild(this.$refs.searchForm);
                } else {
                    this.$refs.searchContainerDesktop.appendChild(this.$refs.searchForm);
                }
            },
            toggleCart(event) {
                if (event.detail && event.detail.isOpen !== undefined) {
                    this.isCartOpen = event.detail.isOpen
                    if (!this.isCartOpen && this.$refs && this.$refs.cartButton) {
                        this.$refs.cartButton.focus()
                    }
                } else {
                    <?php
                    /*
                     * The toggle-cart event was previously dispatched without parameter to open the drawer (not toggle).
                     * Keeping this in here for backwards compatibility.
                     */
                    ?>
                    this.isCartOpen = true
                }
            },
            eventListeners: {
                ['@private-content-loaded.window'](event) {
                    this.getData(event.detail.data);
                },
                ['@resize.window.debounce']() {
                    this.checkIsSearchMobile();
                },
                ['@visibilitychange.window.debounce']() {
                    this.checkIsSearchMobile();
                },
            },
        }
    }
    function initCompareHeader() {
        return {
            compareProducts: null,
            itemCount: 0,
            receiveCompareData(data) {
                if (data['compare-products']) {
                    this.compareProducts = data['compare-products'];
                    this.itemCount = this.compareProducts.count;
                }
            }
        }
    }
</script>
<div
    id="header"
    class="bg-white"
    x-data="initHeader()"
    x-bind="eventListeners"
>
    <?= $block->getChildHtml('header-notification') ?>
    <?= $block->getChildHtml('header-usps'); ?>
    <div class="container text-white bg-[radial-gradient(circle_at_top,_var(--tw-gradient-stops))] from-white via-lego-blue-lighter to-lego-blue-light bg-lego-blue-light lg:bg-transparent lg:bg-none py-3.5 flex gap-12 lg:gap-0 items-center lg:items-end">
        <?= $block->getChildHtml('topmenu.mobile') ?>
        <?= $block->getChildHtml('logo'); ?>

        <div x-ref="searchContainerDesktop"
             class="hidden relative lg:flex lg:ml-12 justify-center order-2
                    min-h-a11y pl-24 pr-0 flex-1 bg-lego-blue-light self-end -mb-3.5 h-20 flex-col rounded-tl-lg
                    before:bg-[url('../images/misterbricks_guy.webp')] before:bg-no-repeat before:absolute before:h-36 before:w-36 before:block before:-left-12 before:bottom-0 before:bg-contain before:bg-left-bottom"></div>
        <div class="flex gap-1 lg:gap-4 items-center order-4 lg:bg-lego-blue-light lg:rounded-tr-lg lg:h-20 lg:-mb-3.5 lg:px-8">

                <?php if ($showMiniCart): ?>
                    <button
                <?php else: ?>
                <a
                <?php endif ?>
                        id="menu-cart-icon"
                        class="relative inline-block rounded p-3 lg:bg-lego-blue-light outline-offset-2 lg:text-white"
                        x-ref="cartButton"
                        :aria-disabled="isCartEmpty()"
                        :aria-label="`
                    <?= $escaper->escapeHtmlAttr($showMiniCart ? __('Toggle minicart') : __('View cart')) ?>,
                    ${isCartEmpty()
                        ? '<?= $escaper->escapeHtmlAttr(__('Cart is empty')) ?>'
                        : cart.summary_count > 1
                            ? hyva.str('<?= $escaper->escapeHtmlAttr(__('%1 items')) ?>', cart.summary_count)
                            : hyva.str('<?= $escaper->escapeHtmlAttr(__('%1 item')) ?>', cart.summary_count)
                    }`"
                    <?php if ($showMiniCart): ?>
                        @click.prevent.stop="() => {
                        $dispatch('toggle-cart', { isOpen: true })
                    }"
                        @toggle-cart.window="toggleCart($event)"
                        :aria-expanded="isCartOpen"
                        aria-haspopup="dialog"
                    <?php else: ?>
                        href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/index')) ?>"
                        title="<?= $escaper->escapeHtmlAttr(__('View cart')) ?>"
                    <?php endif ?>
                >
                    <?= $heroicons->shoppingCartHtml('', 24, 24, ["aria-hidden" => "true"]) ?>
                    <span
                            class="absolute w-7 h-7 -top-1 -right-2 text-sm rounded-full bg-lego-green  border-2 border-white
                            font-semibold text-center uppercase tabular-nums flex justify-center items-center"
                            aria-hidden="true"
                    ><span x-text="cart.summary_count" class="">0</span></span>
                    <?php if ($showMiniCart): ?>
                        </button>
                        <div class="hidden lg:block font-bold text-lg leading-7 text-white"><?= __('Cart') ?></div>
                    <?php else: ?>
                </a>
            <?php endif ?>
            </div>
        <div class="hidden w-16 h-16 bg-contain lg:block lg:ml-12 lg:bg-[url('../images/lego-logo.webp')] order-5"></div>
    </div>

    <div class="lg:bg-gradient-to-b lg:from-lego-menu-light lg:to-lego-menu-dark">
        <div class="relative hidden lg:block">
            <?= $block->getChildHtml('topmenu.desktop') ?>
        </div>
        <div x-ref="searchContainerMobile" class="container bg-lego-blue-light lg:hidden py-4">
            <div x-ref="searchForm">
                <?= $block->getChildHtml('header-search'); ?>
            </div>
        </div>
    </div>

    <?= $block->getChildHtml('cart-drawer'); ?>
    <?= $block->getChildHtml('authentication-popup'); ?>
</div>
